validCommandTable = {'*IDN?': [],
                     '*TST?': [],
                     'BAND:RES': [['int', 3, 600]],
                     'BAND:RES:AUTO': [['bool']],
                     'SYSTem:VERSion?': [],
                     'AMPLitude:ATTenuation': [['int', 0, 31]],
                     'SOURce:POWer:LEVel:IMMediate:AMPLitude': [['str', 'OFF', '30', '15', '10', '4', '3', '2', '1']],
                     '*RST:CONFIGDATA':[],
                     'DISPlay:GRAPhics:COLor?': [],
                     'DISPlay:GRAPhics:COLor': [['int', 0, 65535]],
                     'SENSe:CORRection?': [],
                     'SYSTem:HELP?': [],
                     'SOURce:POWer:LEVel:IMMediate:AMPLitude': [['int', -76, 13]],
                     'SOURCe:POWer:LEVel:IMMediate:AMPLitude:OFFSet': [['int', -70, 70]],
                     'FREQuency:OFFSet?': [],
                     'FREQuency:OFFSet': [['str', 'low', 'high', 'switch']], # Needs tweaking
                     'SYSTem:PRESet': [['int', 0, 4]],
                     'SOURce:DM:FORMat' : [['str', 'off', 'AM_1kHz', 'AM_10Hz', 'NFM', 'WFM', 'extern']],
                     'SOURce:POWer:AMPLitude': [['int', -100, 100]],
                     'OUTPut': [['bool']],
                     'PROGram:SELected:STATe PAUSe': [],
                    }