SCPILookUpTable = {
    "*TST?":"selftest",
    "PROGram:SELected:STATe PAUSe":"pause",
    "PROGram:SELected:STATe CONTinue":"resume",
    "BAND:RES":"rbw",
    "*IDN?":"info",
    'AMPLitude:ATTenuation': 'attenuate',
    'AMPLitude:ATTenuation:AUTO': 'attenuate auto',
    'CONFigure': 'calc',
    'SOURce:POWer:LEVel:IMMediate:AMPLitude': 'caloutput',
    ':HCOPy:SDUMp:DATA?': 'capture',
    '*RST:CLEARCONFIG': 'clearconfig 1234',
    '*RST': 'reset',
    'DISPlay:GRAPhics:COLor?': 'color',
    'DISPlay:GRAPhics:COLor': 'color',
    'SENSe:CORRection': 'correction',
    'SYSTem:SERialnumber?': 'deviceid',
    'SYSTem:SERialnumber': 'deviceid',
    'DISPlay:ENABle': 'refresh',
    'SENSe:CORRection?': 'correction low',
    'SOURce:POWer:LEVel:IMMediate:AMPLitude:OFFset': 'levelchange',
    'SYSTem:MODE': 'mode',
    'SYSTem:VERSion?': 'version',
    'MEASure:SWEep:BEGin:LOW': 'sweep',
    'MEASure:SWEep:BEGin:HIGH': 'sweep',
    'MEASure:SWEep:TIME': 'sweeptime',
    'MEASure:SCAN:RAW:START': 'scanraw',
}
