SCPILookUpTable = {
    "*TST?":"selftest",
    "PROGram:SELected:STATe PAUSe":"pause",
    "PROGram:SELected:STATe CONTinue":"resume",
    "BAND:RES":"rbw",
    "*IDN?":"info",
    'AMPLitude:ATTenuation': 'attenuate',
    'AMPLitude:ATTenuation:AUTO': 'attenuate auto',
    'CONFigure': 'calc',
    'SOURce:POWer:LEVel:IMMediate:AMPLitude': 'caloutput',
    ':HCOPy:SDUMp:DATA?': 'capture',
    '*RST:CONFIGDATA': 'clearconfig',
    'DISPlay:GRAPhics:COLor?': 'color',
    'DISPlay:GRAPhics:COLor': 'color',
    'SENSe:CORRection?': 'correction',
    'SENSe:CORRection': 'correction',
    'SOURce:VOLTage:LEVel:IMMediate:AMPLitude?': 'dac',
    'SOURce:VOLTage:LEVel:IMMediate:AMPLitude': 'dac',
    'TRACe:DATA?': 'data',
    'SYSTem:SERialnumber': 'deviceid',
    'SYSTem:SERialnumber?': 'deviceid',
    'SOURce:FREQuency:FIXed': 'freq',
    'FREQuency:CENTer': 'freq',
    'SOURce:FREQuency:STARt?': 'frequencies',
    'SOURce:FREQuency:STOP?': 'frequencies',
    'SENSe:BANDwidth':'if',
    'SENSe:BWIDth': 'if',
    'SYSTem:HELP?': 'help',
    'SOURce:POWer:LEVel:IMMediate:AMPLitude': 'level',
    'SOURce:POWer:LEVel:IMMediate::AMPLitude:OFFSet': 'levelchange',
    'FREQuency:OFFSet?':'leveloffset',
    'FREQuency:OFFSet?': 'leveloffest'
}